image: mcr.microsoft.com/dotnet/sdk:7.0

stages:
  - build
  - test
  - deploy

before_script:
  - export PROJECT_NAME=profileservice
  - dotnet restore

build:
  stage: build
  script:
    - dotnet build -c Release -o build
    - docker build -t darkmode1/profileservice:latest -t darkmode1/profileservice:$CI_COMMIT_SHA ./build

test:
  stage: test
  script:
    - dotnet test

deploy:
  stage: deploy
  script:
  environment:
    name: production
  only:
    - master
