image: mcr.microsoft.com/dotnet/sdk:7.0

stages:
  - build
  - test
  - deploy

build:
  stage: build
  script:
    - dotnet build -c Release -o build
    - sudo docker build -t darkmode1/profileservice:latest .
    - sudo docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD

test:
  stage: test
  script:
    - dotnet test

deploy:
  stage: deploy
  script:
    - sudo docker push $DOCKER_USERNAME/profileservice
